### ISSUE TITLE
Jarring restart

### ISSUE THREAD

**Issue by awwaiid** [radanskoric/minesvshumanity#1]
It's a bit jarring when the game is ended and then restarted (and I'm not sure that the refresh is very smooth at that point). I suggest a 5-10 second count-down before the next game is initialized.

**Comment by radanskoric** [comment]
@awwaiid , I like that suggestion. I didn’t put much polish on it since it’s more of a demo for the article but what you suggest will be a nice and simple improvement. 👍 At the moment I’m vacationing with family and without laptop but I’ll add it when I’m back.

**Comment by awwaiid** [comment]
Also and maybe more importantly, if you sit on the board and just watch it seems like it stops getting updates esp at the end of the game. I was watching the websocket and it switches to only seeing pings and nothing else. I'd debug but I'm probably supposed to be doing actual $work right now haha

(Very fun demo)

**Comment by radanskoric** [comment]
I'm glad you're finding it fun! I'm actually now seeing quite a few things to improve now. Normally I would not launch something aday before going on vacation , but it was "just a demo". :sweat_smile:

**Comment by radanskoric** [comment]
@awwaiid added the countdown. :) 

I couldn't figure out why ActionCable is not correctly listening to the updates on the new game after doing a JS refresh. I've now switched to a full page reload and noted it down for checking when I have time again. I'm interested to see what it is and if it's something to do with the Morphing refresh. We'll see. 

Thanks for the suggestions!

**Comment by awwaiid** [comment]
It seems a lot better!!
